sudo: required
language: cpp
compiler: gcc
dist: trusty

before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -qq -y libopenblas-dev libgoogle-glog-dev libprotobuf-dev protobuf-compiler
 - sudo apt-get install -qq -y opencl-headers ocl-icd-*
#- wget https://github.com/KhronosGroup/OpenCL-CLHPP/releases/download/v2.0.9/cl2.hpp
#- sudo mv cl2.hpp /usr/include/CL/
#- sudo apt-get install -qq libgtest-dev

before_script:
 - mkdir build && cd build
 - cmake .. -DUSE_CUDA=OFF -DUSE_CUDNN=OFF -DUSE_PYTHON=OFF

script:
 - make
 - ./bin/test_singa --gtest_output=xml:./../gtest.xml

