[package]
name = "pg_extension"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
default = ["pg11", "python"]
python = ["pyo3"]
pg11 = ["pgrx/pg11", "pgrx-tests/pg11" ]
pg12 = ["pgrx/pg12", "pgrx-tests/pg12" ]
pg13 = ["pgrx/pg13", "pgrx-tests/pg13" ]
pg14 = ["pgrx/pg14", "pgrx-tests/pg14" ]
pg15 = ["pgrx/pg15", "pgrx-tests/pg15" ]
pg_test = []

[dependencies]
pgrx = "=0.9.7"
pgrx-pg-sys = "=0.9.7"
serde_json = { version = "1.0.85", features = ["preserve_order"] }
pyo3 = { version = "0.17", features = ["auto-initialize"], optional = true }
once_cell = "1.8.0"
log = "0.4.14"
serde = "1.0"
serde_derive = "1.0"
shared_memory = "0.12.4"

[dev-dependencies]
pgrx-tests = "=0.9.7"

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"
opt-level = 3
lto = "fat"
codegen-units = 1